---
framework: mocha
preRun:
  command:
    - npm install
preMerge:
  env:
      NODE_ENV: test
  pattern:
    - "./test/*.test.js"
postMerge:
  env:
      NODE_ENV: test
  pattern: 
    - "./test/*.test.js"
postRun:
  command:
    - node --version
configFile: mocha.opts
version: 1.0